### ISSUE TITLE
An alternative for this package

### ISSUE THREAD

**Issue by sabloger** [snabb/sitemap#5]
Hi everyone.
As far as neither this package is actively maintained nor any other active package can be found for generating sitemaps in Go, I have made a new one which has an easy usage with great performance.

https://github.com/sabloger/sitemap-generator

**Comment by snabb** [comment]
What kind of maintenance you expected to see? I am happy you are providing an alternative. It is good to have several choices so that one can pick whichever solution is most appropriate for their use case.

**Comment by sabloger** [comment]
I happy you are still watching the the repo. According to the last commit of the project I thought it is out of maintenance. 
Best regards.
